# Generated by Django 5.0.7 on 2024-07-18 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonITApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_itadmissionprocess',
            name='application_deadline',
            field=models.DateField(help_text='Format: YYYY-MM-DD', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='non_itadmissionprocess',
            name='application_start',
            field=models.DateField(help_text='Format: YYYY-MM-DD', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='non_itadmissionprocess',
            name='exam_date',
            field=models.DateField(help_text='Format: YYYY-MM-DD', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
