# Generated by Django 5.0.7 on 2024-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Chocies',
            fields=[
                ('course_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
