# Generated by Django 5.0.7 on 2024-07-16 16:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0002_course_chocies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fee_range', models.CharField(max_length=100)),
                ('class_timing', models.CharField(max_length=100)),
                ('batch_size', models.IntegerField(help_text='Enter a valid batch size', validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_start_date', models.DateField(default=datetime.date.today)),
                ('demo_classes_available', models.BooleanField(default=False)),
                ('demo_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('certification_details', models.TextField(blank=True, null=True)),
                ('mode_of_instruction', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=10)),
                ('language_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.course_chocies')),
                ('it_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute')),
            ],
        ),
    ]
