# Generated by Django 5.0.7 on 2024-07-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0003_itcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItCourse',
        ),
    ]
