# Generated by Django 5.0.7 on 2024-07-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0004_delete_itcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Chocies',
        ),
    ]
