# Generated by Django 5.0.7 on 2024-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0005_delete_course_chocies'),
    ]

    operations = [
        migrations.CreateModel(
            name='It_Course_Chocies',
            fields=[
                ('it_course_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('it_course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
