# Generated by Django 5.0.7 on 2024-07-16 17:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0006_it_course_chocies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItCourse',
            fields=[
                ('it_course_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('duration_days', models.IntegerField(help_text='Enter duration in days (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Enter duration (HH:MM:SS)')),
                ('fee_range', models.CharField(max_length=100)),
                ('class_timing_start', models.TimeField(default=datetime.time(9, 0), help_text='Enter the start time (HH:MM)')),
                ('class_timing_end', models.TimeField(default=datetime.time(17, 0), help_text='Enter the end time (HH:MM)')),
                ('batch_size', models.IntegerField(help_text='Enter a valid batch size', validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_start_date', models.DateField(default=datetime.date.today)),
                ('demo_classes_available', models.BooleanField(default=False)),
                ('demo_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('certification_details', models.TextField(blank=True, null=True)),
                ('mode_of_instruction', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], default='online', max_length=10)),
                ('language_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('it_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.it_course_chocies')),
                ('it_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute')),
            ],
        ),
    ]
