# Generated by Django 5.0.7 on 2024-07-16 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0007_itcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcourse',
            name='batch_size',
            field=models.PositiveIntegerField(help_text='Enter a valid batch size', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
