# Generated by Django 5.0.7 on 2024-07-16 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0008_alter_itcourse_batch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItTrainer',
            fields=[
                ('It_trainer_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('it_trainer_name', models.CharField(max_length=255)),
                ('qualifications', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField(help_text='Enter a valid number of years', validators=[django.core.validators.MinValueValidator(0)])),
                ('specializations', models.TextField()),
                ('achievements', models.TextField()),
                ('it_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.it_course_chocies')),
                ('it_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute')),
            ],
        ),
    ]
