# Generated by Django 5.0.7 on 2024-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0009_ittrainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittrainer',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ittrainer',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
