# Generated by Django 5.0.7 on 2024-07-16 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0010_alter_ittrainer_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItPlacementDetails',
            fields=[
                ('It_Placement_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('placement_statistics', models.DecimalField(blank=True, decimal_places=2, help_text='Enter placement success rate (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('companies_associated', models.TextField(blank=True, help_text='Enter names of companies associated with placements', null=True)),
                ('placement_process', models.TextField(blank=True, help_text='Describe the placement process', null=True)),
                ('success_stories', models.TextField(blank=True, help_text='Share success stories or testimonials', null=True)),
                ('internship_opportunities', models.TextField(blank=True, help_text='Describe internship opportunities', null=True)),
            ],
        ),
    ]
