# Generated by Django 5.0.7 on 2024-07-17 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0012_itcontactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItLocationInformation',
            fields=[
                ('it_location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Address should be at least 5 characters long.'), django.core.validators.RegexValidator(code='invalid_address', message='Address should only contain alphanumeric characters, spaces, dots, commas, dashes, and hash symbols.', regex='^[0-9a-zA-Z\\s\\.,#-]+$')])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pin_code', message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('nearby_landmarks', models.TextField(blank=True)),
            ],
        ),
    ]
