# Generated by Django 5.0.7 on 2024-07-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0013_itlocationinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItFacilitiesAndInfrastructure',
            fields=[
                ('it_facilities_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('classroom_facilities', models.TextField(blank=True, null=True)),
                ('lab_facilities', models.TextField(blank=True, null=True)),
                ('library', models.TextField(blank=True, null=True)),
                ('safety_and_security_measures', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
