# Generated by Django 5.0.7 on 2024-07-17 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0014_itfacilitiesandinfrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItAdmissionProcess',
            fields=[
                ('it_admission_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('admission_requirements', models.TextField()),
                ('application_process', models.TextField()),
                ('application_start', models.DateField(help_text='Format: DD-MM-YYYY', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format DD-MM-YYYY.', regex='^\\d{2}-\\d{2}-\\d{4}$')])),
                ('application_deadline', models.DateField(help_text='Format: DD-MM-YYYY', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format DD-MM-YYYY.', regex='^\\d{2}-\\d{2}-\\d{4}$')])),
                ('exam_date', models.DateField(help_text='Format: DD-MM-YYYY', validators=[django.core.validators.RegexValidator(code='invalid_date_format', message='Date must be in the format DD-MM-YYYY.', regex='^\\d{2}-\\d{2}-\\d{4}$')])),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Admission fee cannot be negative.'), django.core.validators.MaxValueValidator(1000000, message='Admission fee exceeds maximum allowed amount.')])),
                ('scholarships', models.TextField(blank=True, null=True)),
                ('entrance_exams_accepted', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_process', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
