# Generated by Django 5.0.7 on 2024-07-17 05:55

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0015_itadmissionprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='itadmissionprocess',
            name='it_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute'),
        ),
        migrations.AddField(
            model_name='itfacilitiesandinfrastructure',
            name='it_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute'),
        ),
        migrations.AddField(
            model_name='itplacementdetails',
            name='it_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute'),
        ),
        migrations.CreateModel(
            name='ItContactAndSupportForm',
            fields=[
                ('it_support_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('it_support_person', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('email_address', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('office_hour_start', models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value='08:00'), django.core.validators.MaxValueValidator(limit_value='18:00')])),
                ('office_hour_end', models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value='08:00'), django.core.validators.MaxValueValidator(limit_value='18:00')])),
                ('support_services', models.TextField(blank=True, null=True)),
                ('faqs', models.TextField(blank=True, null=True)),
                ('it_institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute')),
            ],
        ),
    ]
