# Generated by Django 5.0.7 on 2024-07-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0017_itcontactinformation_it_institute_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItCourse',
        ),
    ]
