# Generated by Django 5.0.7 on 2024-07-17 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0019_itcourseform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItAdditionalInformation',
            fields=[
                ('it_additional_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('other_social_media_links', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('events_seminars', models.TextField(blank=True, null=True)),
                ('news_updates', models.TextField(blank=True, null=True)),
                ('it_institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITApp.itinstitute')),
            ],
        ),
    ]
