# Generated by Django 5.0.7 on 2024-07-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0020_itadditionalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itplacementdetails',
            name='placement_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
