# Generated by Django 5.0.7 on 2024-07-17 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0021_itplacementdetails_placement_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstitute',
            name='website_url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
