# Generated by Django 5.0.7 on 2024-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0022_alter_itinstitute_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcontactinformation',
            name='office_hour_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itcontactinformation',
            name='office_hour_start',
            field=models.TimeField(),
        ),
    ]
