# Generated by Django 5.0.7 on 2024-07-17 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0023_alter_itcontactinformation_office_hour_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itcontactinformation',
            name='office_hour_end',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value='06:00'), django.core.validators.MaxValueValidator(limit_value='20:00')]),
        ),
        migrations.AlterField(
            model_name='itcontactinformation',
            name='office_hour_start',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(limit_value='06:00'), django.core.validators.MaxValueValidator(limit_value='20:00')]),
        ),
    ]
