# Generated by Django 5.0.7 on 2024-07-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0026_alter_itadmissionprocess_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itplacementdetails',
            name='mock_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itplacementdetails',
            name='mock_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itplacementdetails',
            name='softskills',
            field=models.BooleanField(default=False),
        ),
    ]
