# Generated by Django 5.0.7 on 2024-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITApp', '0028_alter_itinstitute_it_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinstitute',
            name='it_institute_name',
            field=models.CharField(max_length=255),
        ),
    ]
